# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Vitest

on:
  pull_request:
    paths:
      - .github/workflows/js-test.yml
      - src/**
      - package.json
      - package-lock.json
      - vitest.config.*
  push:
    branches:
      - main
      - stable*
    paths:
      - .github/workflows/js-test.yml
      - src/**
      - package.json
      - package-lock.json
      - vitest.config.*

permissions:
  contents: read

concurrency:
  group: vitest-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  vitest:
    runs-on: ubuntu-latest
    name: vitest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: "^20"
          fallbackNpm: "^9"

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
